name: Workflow 1

on:
  pull_request:
    branches: [development]
    types: [closed]
  push:
    # branches-ignore:
    # - INF-1205-keyvault
    branches: [actions]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        run: echo "Deploying application..."
