name: workflow for running test pipeline
on:
  pull_request:
    branches:
      - development
    types:
      - closed
  push:
    branches:
      - main
      - master
env:
    ACTION_STEP_DEBUG: true
    PACKER_PRODUCT_VERSION: 1.8.5
    TERRAFORM_PRODUCT_VERSION: 1.7.3
    ENVIRONMENT: "Development"
    ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
    ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
    ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
    ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
    ACTIONS_STEP_DEBUG: true
jobs:
  tools_check:
    name: 'checking_tools_status'
    runs-on: ubuntu-latest
    steps:
    - name: print runner hostname
      run: hostname
      shell: bash
    - name: print runner ip address
      run: curl -sL https://ipconfig.io
      shell: bash
    - name: Setup terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_PRODUCT_VERSION }}
    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: ${{ env.PACKER_PRODUCT_VERSION }}
    - name: Check Terraform and Packer Version
      run: terraform version && packer version
      shell: bash
  terraform_init:
    needs: tools_check
    name: 'Files check and Terraform init'
    runs-on: ubuntu-latest
    defaults:
        run:
            shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: list repo files
      run: |
        ls -al
        pwd
        free
    - name: Perform Terraform Init and Apply
      id: init
      shell: bash
      run: |
        # terraform init && terraform apply --auto-approve
        # terraform state list
        bash frontdoor.sh