name: test-dispatch
on:
  pull_request:
    branches: [development]
    types: [closed]
  push:
    # branches-ignore:
    # - INF-1205-keyvault
    # - 
    branches: [actions]
  workflow_dispatch:
    inputs:
      example_input:
        description: 'Example input'
        required: true
        type: choice
        options:
        - OPTION_1
        - OPTION_2

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - name: Print input
      run: echo "Input is ${{ github.event.inputs.example_input }}"
